export enum VenueType {
  STORE = 'store',
  SUPERMARKET = 'supermarket',
  RESTAURANT = 'restaurant',
  CAFE = 'cafe',
  BAR = 'bar',
  DELIVERY = 'delivery',
  STREET_FOOD = 'street_food',
  ZOO = 'zoo',
  CINEMA = 'cinema',
  GAS_STATION = 'gas_station',
  PHARMACY = 'pharmacy',
  SERVICE = 'service',
  ONLINE = 'online',
  HOTEL = 'hotel',
  AIRPORT = 'airport',
  TRAIN_STATION = 'train_station',
  EVENT_VENUE = 'event_venue',
  MUSEUM = 'museum',
  PARK = 'park',
  OTHER = 'other',
}
